### ISSUE TITLE
Some Problem in Chinese Version Client

### ISSUE THREAD

**Issue by 1369521908** [LoL-Fantome/Fantome#59]
09-09-2020 21:06:21.116 | [Information] |  Starting Index Edit
09-09-2020 21:06:21.156 | [Information] |  Removed Mod: KDA Ashe - 1.0 (by Yoru) from WAD: DATA\FINAL\Champions\Ashe.wad.client in WAD Mod Map
09-09-2020 21:06:21.156 | [Information] |  Commited Index changes
09-09-2020 21:06:22.296 | [Information] |  Installing Mod: KDA Ashe - 1.0 (by Yoru)
09-09-2020 21:06:22.296 | [Information] |  Starting Index Edit
09-09-2020 21:06:22.297 | [Information] |  Added Mod: KDA Ashe - 1.0 (by Yoru) to WAD: DATA\FINAL\Champions\Ashe.wad.client
09-09-2020 21:06:22.419 | [Information] |  Commited Index changes
09-09-2020 21:06:25.716 | [Information] |  PATCHER: Found League process
09-09-2020 21:06:25.757 | [Information] |  PATCHER: Updating offsets
09-09-2020 21:06:26.165 | [Error] |  PATCHER: System.IO.IOException: Failed to update offsets!
   at LoLCustomSharp.OverlayPatcher.UpdateOffsets(LeagueProcess league)
   at LoLCustomSharp.OverlayPatcher.<>c__DisplayClass28_0.<Start>b__0()

**Comment by TheKillerey** [comment]
Chinese is protected by Tencent and this makes the error because it blocks fantome to update the offsets. The only way it to bypass it.

**Comment by 1369521908** [comment]
OK Thanks~

**Comment by yassuoking** [comment]
I already have another one that I can use in China.It is named ''格子挂载器''.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LoL-Fantome/Fantome"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 晚上10:13
收件人:&nbsp;"LoL-Fantome/Fantome"<Fantome@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [LoL-Fantome/Fantome] Some Problem in Chinese Version Client (#59)





 
Chinese is protected by Tencent and this makes the error because it blocks fantome to update the offsets. The only way it to bypass it.

**Comment by TheKillerey** [comment]
Bye bye Windows protection.
